DROP DATABASE IF EXISTS CHESS_CHALLENGE;
CREATE DATABASE CHESS_CHALLENGE;

CREATE TABLE IF NOT EXISTS WINNERS (
    white INTEGER,
    black INTEGER,
    no_winner INTEGER
);

CREATE TABLE IF NOT EXISTS PIECES (
    bishop INTEGER,
    king INTEGER,
    knight INTEGER,
    pawn INTEGER,
    queen INTEGER,
    rook INTEGER
);

-- INSERT INTO WINNERS VALUES (0,0,0);
-- INSERT INTO PIECES VALUES (0,0,0,0,0,0);