DROP DATABASE IF EXISTS CHESS_CHALLENGE;
CREATE DATABASE CHESS_CHALLENGE;

DROP TABLE WINNERS;
DROP TABLE PIECES;
CREATE TABLE IF NOT EXISTS WINNERS (
    id SERIAL CONSTRAINT winners_pk PRIMARY KEY,
    winner VARCHAR(9) NOT NULL CHECK (winner IN ('white', 'black', 'none'))
);

CREATE TABLE IF NOT EXISTS PIECES (
    id SERIAL CONSTRAINT pieces_pk PRIMARY KEY,
    piece VARCHAR(6) NOT NULL CHECK (piece IN ('bishop', 'knight', 'pawn', 'queen', 'rook'))
);

INSERT INTO WINNERS (winner) VALUES ('none');
INSERT INTO WINNERS (winner) VALUES ('white');
INSERT INTO WINNERS (winner) VALUES ('black');

INSERT INTO PIECES (piece) VALUES ('queen');
INSERT INTO PIECES (piece) VALUES ('bishop');
INSERT INTO PIECES (piece) VALUES ('queen');