/*
 * This file is generated by jOOQ.
 */
package com.chess_challenge.java_1.statistics.repositories.jooq.db.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PiecesQueryBuilder implements Serializable {

    private static final long serialVersionUID = 1104474351;

    private final String  piece;
    private final Integer matches;

    public PiecesQueryBuilder(PiecesQueryBuilder value) {
        this.piece = value.piece;
        this.matches = value.matches;
    }

    public PiecesQueryBuilder(
        String  piece,
        Integer matches
    ) {
        this.piece = piece;
        this.matches = matches;
    }

    public String getPiece() {
        return this.piece;
    }

    public Integer getMatches() {
        return this.matches;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("PiecesQueryBuilder (");

        sb.append(piece);
        sb.append(", ").append(matches);

        sb.append(")");
        return sb.toString();
    }
}
