/*
 * This file is generated by jOOQ.
 */
package com.chess_challenge.java_1.statistics.repositories.jooq.db.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class WinnersQueryBuilder implements Serializable {

    private static final long serialVersionUID = 657770375;

    private final String  winner;
    private final Integer matches;

    public WinnersQueryBuilder(WinnersQueryBuilder value) {
        this.winner = value.winner;
        this.matches = value.matches;
    }

    public WinnersQueryBuilder(
        String  winner,
        Integer matches
    ) {
        this.winner = winner;
        this.matches = matches;
    }

    public String getWinner() {
        return this.winner;
    }

    public Integer getMatches() {
        return this.matches;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("WinnersQueryBuilder (");

        sb.append(winner);
        sb.append(", ").append(matches);

        sb.append(")");
        return sb.toString();
    }
}
