/*
 * This file is generated by jOOQ.
 */
package com.chess_challenge.java_1.statistics.repositories.jooq.db.tables;


import com.chess_challenge.java_1.statistics.repositories.jooq.db.Keys;
import com.chess_challenge.java_1.statistics.repositories.jooq.db.Public;
import com.chess_challenge.java_1.statistics.repositories.jooq.db.tables.records.WinnersQueryBuilderRecord;

import java.util.Arrays;
import java.util.List;

import org.jooq.Check;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class WinnersQueryBuilder extends TableImpl<WinnersQueryBuilderRecord> {

    private static final long serialVersionUID = 201399403;

    /**
     * The reference instance of <code>public.winners_query_builder</code>
     */
    public static final WinnersQueryBuilder WINNERS_QUERY_BUILDER = new WinnersQueryBuilder();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<WinnersQueryBuilderRecord> getRecordType() {
        return WinnersQueryBuilderRecord.class;
    }

    /**
     * The column <code>public.winners_query_builder.winner</code>.
     */
    public final TableField<WinnersQueryBuilderRecord, String> WINNER = createField(DSL.name("winner"), org.jooq.impl.SQLDataType.VARCHAR(9).nullable(false), this, "");

    /**
     * The column <code>public.winners_query_builder.matches</code>.
     */
    public final TableField<WinnersQueryBuilderRecord, Integer> MATCHES = createField(DSL.name("matches"), org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * Create a <code>public.winners_query_builder</code> table reference
     */
    public WinnersQueryBuilder() {
        this(DSL.name("winners_query_builder"), null);
    }

    /**
     * Create an aliased <code>public.winners_query_builder</code> table reference
     */
    public WinnersQueryBuilder(String alias) {
        this(DSL.name(alias), WINNERS_QUERY_BUILDER);
    }

    /**
     * Create an aliased <code>public.winners_query_builder</code> table reference
     */
    public WinnersQueryBuilder(Name alias) {
        this(alias, WINNERS_QUERY_BUILDER);
    }

    private WinnersQueryBuilder(Name alias, Table<WinnersQueryBuilderRecord> aliased) {
        this(alias, aliased, null);
    }

    private WinnersQueryBuilder(Name alias, Table<WinnersQueryBuilderRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    public <O extends Record> WinnersQueryBuilder(Table<O> child, ForeignKey<O, WinnersQueryBuilderRecord> key) {
        super(child, key, WINNERS_QUERY_BUILDER);
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public UniqueKey<WinnersQueryBuilderRecord> getPrimaryKey() {
        return Keys.WINNERS_QUERY_BUILDER_PK;
    }

    @Override
    public List<UniqueKey<WinnersQueryBuilderRecord>> getKeys() {
        return Arrays.<UniqueKey<WinnersQueryBuilderRecord>>asList(Keys.WINNERS_QUERY_BUILDER_PK);
    }

    @Override
    public List<Check<WinnersQueryBuilderRecord>> getChecks() {
        return Arrays.<Check<WinnersQueryBuilderRecord>>asList(
              Internal.createCheck(this, DSL.name("winners_query_builder_winner_check"), "(((winner)::text = ANY ((ARRAY['white'::character varying, 'black'::character varying, 'none'::character varying])::text[])))", true)
        );
    }

    @Override
    public WinnersQueryBuilder as(String alias) {
        return new WinnersQueryBuilder(DSL.name(alias), this);
    }

    @Override
    public WinnersQueryBuilder as(Name alias) {
        return new WinnersQueryBuilder(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public WinnersQueryBuilder rename(String name) {
        return new WinnersQueryBuilder(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public WinnersQueryBuilder rename(Name name) {
        return new WinnersQueryBuilder(name, null);
    }

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row2<String, Integer> fieldsRow() {
        return (Row2) super.fieldsRow();
    }
}
