/*
 * This file is generated by jOOQ.
 */
package com.chess_challenge.java_1.statistics.repositories.jooq.db;


import com.chess_challenge.java_1.statistics.repositories.jooq.db.tables.PiecesQueryBuilder;
import com.chess_challenge.java_1.statistics.repositories.jooq.db.tables.WinnersQueryBuilder;
import com.chess_challenge.java_1.statistics.repositories.jooq.db.tables.records.PiecesQueryBuilderRecord;
import com.chess_challenge.java_1.statistics.repositories.jooq.db.tables.records.WinnersQueryBuilderRecord;

import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>public</code> schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<PiecesQueryBuilderRecord> PIECES_QUERY_BUILDER_PK = UniqueKeys0.PIECES_QUERY_BUILDER_PK;
    public static final UniqueKey<WinnersQueryBuilderRecord> WINNERS_QUERY_BUILDER_PK = UniqueKeys0.WINNERS_QUERY_BUILDER_PK;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class UniqueKeys0 {
        public static final UniqueKey<PiecesQueryBuilderRecord> PIECES_QUERY_BUILDER_PK = Internal.createUniqueKey(PiecesQueryBuilder.PIECES_QUERY_BUILDER, "pieces_query_builder_pk", new TableField[] { PiecesQueryBuilder.PIECES_QUERY_BUILDER.PIECE }, true);
        public static final UniqueKey<WinnersQueryBuilderRecord> WINNERS_QUERY_BUILDER_PK = Internal.createUniqueKey(WinnersQueryBuilder.WINNERS_QUERY_BUILDER, "winners_query_builder_pk", new TableField[] { WinnersQueryBuilder.WINNERS_QUERY_BUILDER.WINNER }, true);
    }
}
