/*
 * This file is generated by jOOQ.
 */
package com.chess_challenge.java_1.statistics.repositories.jooq.db;


import com.chess_challenge.java_1.statistics.repositories.jooq.db.tables.PiecesQueryBuilder;
import com.chess_challenge.java_1.statistics.repositories.jooq.db.tables.WinnersQueryBuilder;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = -575420340;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.pieces_query_builder</code>.
     */
    public final PiecesQueryBuilder PIECES_QUERY_BUILDER = PiecesQueryBuilder.PIECES_QUERY_BUILDER;

    /**
     * The table <code>public.winners_query_builder</code>.
     */
    public final WinnersQueryBuilder WINNERS_QUERY_BUILDER = WinnersQueryBuilder.WINNERS_QUERY_BUILDER;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.<Table<?>>asList(
            PiecesQueryBuilder.PIECES_QUERY_BUILDER,
            WinnersQueryBuilder.WINNERS_QUERY_BUILDER);
    }
}
