/*
 * This file is generated by jOOQ.
 */
package com.chess_challenge.java_1.statistics.repositories.jooq.db;


import com.chess_challenge.java_1.statistics.repositories.jooq.db.tables.PiecesQueryBuilder;
import com.chess_challenge.java_1.statistics.repositories.jooq.db.tables.WinnersQueryBuilder;


/**
 * Convenience access to all tables in public
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.pieces_query_builder</code>.
     */
    public static final PiecesQueryBuilder PIECES_QUERY_BUILDER = PiecesQueryBuilder.PIECES_QUERY_BUILDER;

    /**
     * The table <code>public.winners_query_builder</code>.
     */
    public static final WinnersQueryBuilder WINNERS_QUERY_BUILDER = WinnersQueryBuilder.WINNERS_QUERY_BUILDER;
}
